map_server:
  ros__parameters:
    use_sim_time: ${use_sim_time}
    yaml_filename: "pal_office.yaml"

map_saver:
  ros__parameters:
    use_sim_time: ${use_sim_time}
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True
